version: "3.8"

services:
    app:
        build: .
        container_name: node_app
        restart: always
        depends_on:
            - mongo
            - redis
            - rabbitmq
        environment:
            - PORT=3000
            - MONGO_URI=mongodb://admin:admin123@mongo:27017/
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules

    mongo:
        image: mongo:latest
        container_name: mongodb_container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin123
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:latest
        container_name: redis_cache
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672" # Interface web do RabbitMQ
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

volumes:
    mongo_data:
    redis_data:
